# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - build-test
  - build-master

before_script:
  - docker version
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build-master
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-test:
  stage: build-test
  script:
    - docker build --no-cache -t drupal8-ci .
    - docker build --no-cache -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -f Dockerfile-test .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"